#!/bin/csh -f
#
# Sript name: mailtomaillist
# Example:    9.93
#

foreach person (`cat maillist`)
   mail $person <<EOF
      Hi $person,
      How are you?  I've missed you. Come on over
      to my place. 
      Your pal,
	    $LOGNAME@`uname -n`
EOF
end
