#!/bin/sh
# File: perm_check2
# Using the old style test command
file=./testing

if [[ -d $file ]]  
then
   echo "$file is a directory"
elif [[ -f $file ]]
then
   if [[  -rwx $file ]]
   then                         # nested if command
      echo "You have read,write,and execute \
            permission on $file."
   fi
else
   echo  "$file is neither a file nor a directory. "
fi

