#!/bin/csh -f
#
# Script name: colors
# Example:     9.90
#

echo -n "Which color do you like? "
set color = $<
switch ("$color")
case bl*:
   echo I feel $color
   echo The sky is $color
   breaksw 
case red:          # Is is red or is it yellow?       
case yellow:
   echo The sun is sometimes $color.
   breaksw
default:
   echo $color not one of the categories.
   breaksw                
endsw
