#!/bin/ksh
# Script name: quiz
# Example 10.102

read answer?"Who was the U.S. President in 1992? "
while [[ $answer != "Bush" ]]
do
    print "Wrong try again!"
    read answer
done
print Good guess!

